apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cap-orders-app-host-instance
spec:
  clusterServiceClassExternalName: html5-apps-repo
  clusterServicePlanExternalName: app-host
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: cap-orders-app-host-binding
spec:
  instanceRef:
    name: cap-orders-app-host-instance
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cap-orders-destination-instance
spec:
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite
  parameters:
    HTML5Runtime_enabled: true
    version: "1.0.0"
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: cap-orders-destination-binding
spec:
  instanceRef:
    name: cap-orders-destination-instance